### ISSUE TITLE
Bug: realtime parser returns duplicate vehicles

### ISSUE THREAD

**Issue by jamespfennell** [jamespfennell/gtfs#8]
When I parse the most recent GTFS realtime feed for the NYC L train I see many duplicate vehicles in the result. One vehicle has `IsEntityInMessage: false` and the other has `IsEntityInMessage: true`. Presumably the parser sees the first vehicle attached to a `TripUpdate` and the second attached to a `VehiclePosition`. It should de-duplicate these - in fact, the `IsEntityInMessage: false` vehicle should just be dropped in this case.

Observed after https://github.com/jamespfennell/transiter/pull/110 was submitted to Transiter mainline. In Transiter I see lots of debug logging warning of duplicate vehicles in the NYC subway feed, and I think the root cause is here.

CC @cedarbaum.

**Comment by jamespfennell** [comment]
Started working on this in https://github.com/jamespfennell/gtfs/tree/duplicate-vehicles

**Comment by jamespfennell** [comment]
Ahhhhh the root cause is pretty subtle. When we're parsing entities we de-duplicate vehicles using a map keyed on `VehicleID` whose current definition is:

```
type VehicleID struct {
	ID           *string
	Label        *string
	LicencePlate *string
}
```

The problem is that even if the values of the `ID` fields match after following the pointer, Go considers them distinct from a hashing perspective because the pointers themselves are different. I think the simplest solution would be to remove the pointers:
```
type VehicleID struct {
	ID           string
	Label        string
	LicencePlate string
}
```
and interpret a field being `""` as equivalent to the field not being provided in the GTFS realtime feed. In theory the feed could have `Label: &""` but I think this edge case is not a big deal.

**Comment by cedarbaum** [comment]
Great catch, thanks so much for fixing this!
